### ISSUE TITLE
[Proposal] Let stew browse accept url to gh repo  

### ISSUE THREAD

**Issue by edshamis** [marwanhawari/stew#13]
This way, one can just copy and use the url, no need to select the ending part

**Comment by marwanhawari** [comment]
Thanks for the feedback! I understand why someone would want this, but I'm going to stick to the 2 ways that users can currently use stew:
1. Provide the GitHub owner/repo
2. Provide a URL directly to a binary/script (doesn't have to be on GitHub)

I don't want to introduce a 3rd way where if you provide a GitHub repo URL specifically, then it acts like case #1. I also don't want this proposal to replace case #1 because I don't think stew should only accept URLs. I want stew to have a simple, consistent, and predictable command line usage.
